# Whether or not the EnderDragon destroys blocks.
DestroyBlocks: false
# Whether or not the EnderDragon spawns an egg. If set to true while the portal
# is disabled, it will drop as an item rather than being placed as a block.
SpawnEgg: true
# Whether or not EnderDragon eggs teleport when hit by a player. This setting is
# to help disable creative theft, especially since LogBlock doesn't log the egg
# being teleported.
EggsCanTeleport: false
# The maximum time it takes for a dragon to respawn.
MaxRespawnMinutes: 5
# The minimum time it takes for a dragon to respawn.
MinRespawnMinutes: 5
# Whether to drop exp to ground (as in vanilla) or give it directly to players
DropEXP: false
# The time it takes for a player who has received experience from the
# EnderDragon to be able to receive more.
EXPResetMinutes: 1200
# The maximum distance from the EnderDragon a player must be to receive
# experience from the kill.
EXPMaxDistance: 75
# The custom amount of experience to award players who have slain the
# EnderDragon.
# NOTE: The default value, 20000, gives 105 levels.
EXPTotal: 20000
# Worlds in which the Enderdragon will spawn.
Worlds:
  # The name of the world to manage. Not case sensitive.
  world_the_end:
    # The actual spawn point for the world.
    SpawnPoint:
      X: 0
      Y: 128
      Z: 0
