name: EnderSpawn
version: 0.1
description: This plugin adds a dynamic control system for the Enderdragon in The End.
author: Glitchfinder 
website: https://github.com/Glitchfinder/EnderSpawn

main: org.enderspawn.EnderSpawn
