name: EnderSpawn
version: ${project.version}
description: >
  This plugin adds a dynamic control system for the Enderdragon in The End.
author: Glitchfinder 
website: https://github.com/Glitchfinder/EnderSpawn

main: org.enderspawn.EnderSpawn

commands:
  enderspawn:
    description: Enderspawn command.
    aliases: ['es']
    usage: >
      /<command>
      [reload
      | ban [playername] [reason]
      | unban [playername]
      | lookup [playername]
      | status <playername>
      | reset [playername]]

permissions:
  enderspawn.*:
    description: >
      Access to EVERYTHING related to the EnderSpawn plugin.
    children:
      enderspawn.ban: true
      enderspawn.reload: true
      enderspawn.lookup: true
      enderspawn.status: true
      enderspawn.status.other: true
      enderspawn.exp: true
      enderspawn.unlimitedexp: true
      enderspawn.reset: true
  enderspawn.admin:
    description: >
      Access to everything related to the EnderSpawn plugin.
    children:
      enderspawn.ban: true
      enderspawn.reload: true
      enderspawn.lookup: true
      enderspawn.status: true
      enderspawn.status.other: true
      enderspawn.exp: true
      enderspawn.unlimitedexp: true
      enderspawn.reset: true
  enderspawn.ban:
    description: >
      Access to the /enderspawn ban and /enderspawn unban commands.
    default: op
  enderspawn.reload:
    description: >
      Access to the /enderspawn reload command.
    default: op
  enderspawn.lookup:
    description: >
      Access to the /enderspawn lookup command.
    default: op
  enderspawn.status:
    description: >
      Access to the /enderspawn status command.
    default: true
  enderspawn.status.other:
    description: >
      Access to the /enderspawn status <playername> command.
    default: op
  enderspawn.exp:
    description: >
      Access to the experience dropped by the EnderDragon.
    default: true
  enderspawn.unlimitedexp:
    description: >
      Access to the experience dropped by the EnderDragon, without the cooldown.
    default: op
  enderspawn.reset:
    description: >
      Access to the /enderspawn reset command.
    default: op
